version: '3.9'

services:
    nginx:
        container_name: my_nginx
        image: nginx:latest
        ports:
            - "9889:80"
        volumes:
            - ./www:/var/www
            - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf            
        networks:
            my-network:
                ipv4_address: 10.5.0.5


networks:
    my-network:
        driver: bridge
        ipam:
            config:
              - subnet: 10.5.0.0/16
                gateway: 10.5.0.1
